/* ui-core.js — 描画層の共通部：ui内ローカル文言(TX2)・t2・合否ラベル・一覧行の状態表示
   ※ js/ui.js を機械的に分割したもの（プレーンスクリプト・グローバル名は不変）。読み込み順は ui-core → ui-exam → ui-score → ui-hist → ui-chart → ui-cfg */
/* ==============================================================
   ui.js内ローカル文言（i18n.jsはコンテンツ担当が編集中のため触らない。
   ja/en/vi/id の4言語すべてに入れる。欠けは tests/i18n.test.js で検出。sumTimes1 は英語の単数形専用）
   ============================================================== */
const TX2={
ja:{wakeNote:'録音中は画面を消さないでください（消えると録音はそこで止まります）',recCut:'録音が途中で止まりました（{s}秒まで保存）。マイクを他のアプリや通話に取られた可能性があります。続きは「続きを録音」で録ってください',recCutStat:'途中で停止（{s}秒まで保存）',recHidStop:'画面が消えたため録音を止めました（{s}秒まで保存）。続きは「続きを録音」で録ってください',recPause:'一時停止',recResume:'再開',recPaused:'一時停止中',pauseNA:'この端末では一時停止できません',recCont:'続きを録音',recAppended:'続きを前の録音の後ろに追加しました',mergeFail:'続きを前の録音につなげませんでした。前の録音はそのまま残っています（続きの部分はダウンロードできます）',mergeFailStat:'続きをつなげませんでした（前の録音は無事）',liveFound:'中断された録音があります：{e}／{q}（約{s}秒・{t}）',liveMore:'ほか{n}件',liveRestore:'中断された録音を復元',liveDiscard:'破棄',liveDiscardQ:'中断された録音を削除します。元に戻せません。よろしいですか？',liveRestored:'中断された録音を復元しました',liveNoSess:'戻し先の試問がありません。先に今の試問を保存してから復元するか、ダウンロードしてください',liveReplace:'この問にはすでに録音があります。中断された録音で置き換えますか？',undoClose:'閉じる',pfCleared:'合否を取り消しました（未判定）',beepOpt:'録音の開始・停止を短い音で知らせる（振動は対応端末で常に）',
noItems:'質問がありません。設定タブで質問を追加するか、質問セットを選んでください',noItemsT:'質問がありません',goCfg:'設定タブで質問を追加',pickSet:'質問セットを選ぶ',
drvConnNoAuto:'● 接続OK・ただし自動保存はOFF（録音はこの端末だけ。下のチェックでONにできます）',gAutoOn:'録音の自動保存をONにしました',gAutoWait:'接続を確認しています。つながれば録音の自動保存をONにします',gAutoPend:'自動保存は接続を確認できてからONになります（URLと合言葉を確かめて「接続テスト」）',drvOn:'☁ ドライブ自動保存：ON',drvOff:'☁ ドライブ自動保存：OFF（録音は端末のみ）',drvNone:'☁ ドライブ：未設定（録音は端末のみ）',drvHint:'録音はこの端末だけに保存されます（ドライブ保存は「設定」タブ）',drvHintGo:'ドライブを設定',needEe:'先に受験者名を入力してください（ドライブではこの名前のフォルダに保存されます）',eeSwitch:'{o}さんの録音{n}問・合否{m}問がまだ保存されていません。\n\nOK＝{o}さんの分を保存してから、{e}さんの試問を始める\nキャンセル＝名前の訂正だけ（今の録音と合否は{e}さんのものになります）',eeSwitched:'{o}さんの試問を保存しました。{e}さんの試問を始めます',eeSwitchFail:'{o}さんの試問を保存できなかったため、名前を元に戻しました',
saveErrMsg:'試問を保存できませんでした（端末の空き容量不足の可能性）。入力と録音はこの画面に残っています。先にバックアップを書き出してから、不要なデータを消して「もう一度保存」を押してください',retrySave:'もう一度保存',
recSaveFail:'録音を端末に保存できませんでした',recKeptOld:'（前の録音が残っています）',recRetryStore:'保存し直す',recDl:'この録音をダウンロード',pendTakeSave:'端末に保存できていない録音が{n}件あります。このまま保存するとその録音は失われます。\n先に各問の「保存し直す」か「この録音をダウンロード」で取り出してください。\n\nそれでも保存しますか？（キャンセル＝保存しないで戻る）',pendTakeReset:'（端末に保存できていない録音{n}件も失われます。先にダウンロードしてください）',
micInsecure:'この画面ではマイクを使えません。https:// のアドレスで開いてください',micInsecureS:'マイク不可—httpsで開く',
micNotFound:'マイクが見つかりません。イヤホン・マイクの接続を確認してください',micNotFoundS:'マイクが見つかりません',
micBusy:'他のアプリがマイクを使用中です。通話やBluetoothイヤホンを終了してから録音してください',micBusyS:'マイク使用中（通話を終了）',
drvFailToast:'Googleドライブへ送れませんでした。電波が戻ったら自動で再送します（各問の「☁未送信」をタップでも再送）',drvUnsent:'☁ 未送信（タップで再送）',
oldN:'旧評価{n}問',oldAvg:'旧評価 平均',oldTag:'旧',unconf:'（未確定）',stPending:'判定済み・確定待ち',notAsked:'（未実施）',
oldReplace:'旧5段階評価（{v}）を合否に置き換えますか？（元の点数は消えます）',oldNA:'旧5段階評価（{v}）を消して「質問しなかった」にしますか？',
confirmScored:'録音した全問に合否が付いています。採点も確定しますか？\n（キャンセルすると録音のみで保存し、あとで採点タブから確定できます）',
oldOnly:'旧5段階評価の記録のみです（合格率の対象外）。履歴タブで点数を確認できます',
mixNote:'※旧5段階評価が混ざる試問は、合否を付けた設問だけで合格率を計算しています（旧評価の設問は含みません）',
chPending:'判定済み・確定待ちの試問があります。「採点」タブで開いて「採点を保存」するとグラフに表示されます',
stPartial:'採点途中',partLbl:'合格{p}・判定{j}/録音{m}',chPartial:'○×が途中までの試問（採点途中）があります。「採点」タブで残りの合否を付けて「採点を保存」するとグラフに表示されます',
pfProg:'合否 {j} / 録音 {n}',pfMiss:'○×未入力 {n}問',nextUnjudged:'次の未判定へ',allJudged:'録音した問はすべて○×済みです',
savedScored:'試問と採点を保存しました。結果は「履歴」タブで確認できます',cfgSavedSet:'項目を保存しました（セット「{n}」にも反映）',
qsTitle:'試問セット',qsCur:'現在のセット',qsNone:'（セット未保存の構成）',qsSaveNew:'名前を付けて別のセットに保存',qsApply:'切替',qsRen:'名前変更',qsDel:'削除',
qsNamePrompt:'セット名を入力してください（例：新人向け／繁殖担当／棚倉農場）',
qsSwConfirm:'セット「{n}」の保存済みの内容に切り替えます。「項目を保存」していない編集は失われます（過去の試問データは消えません）。よろしいですか？',
qsDelConfirm:'セット「{n}」を削除しますか？（過去の試問データは消えません）',
qsSaved:'セットを保存しました',qsApplied:'セットに切り替えました',qsDeleted:'セットを削除しました',
qbTitle:'プリセット試問セット（テンプレート）',qbReplace:'項目を置き換え',qbAppend:'項目に追記',
qbRepConfirm:'現在の試問項目をプリセット「{n}」で置き換えます（過去の試問データは消えません）。よろしいですか？',
qbApplied:'プリセットを適用しました',qbNone:'プリセット（qbank.js）が読み込まれていません',
dirty:'未保存の変更があります',dirtyLeave:'試問項目に未保存の変更があります。保存せずに移動しますか？（変更は破棄されます）',
delSecConfirm:'このセクションと全質問を削除しますか？',cfgNote:'※質問を削除・差し替えても、過去の試問の採点・録音・文字起こしは履歴とCSVに残ります',
storeFail:'保存に失敗しました（端末の空き容量不足の可能性）。設定タブからバックアップの書き出しをおすすめします',
gcConfirm:'どのセッションにも属さない録音データが{n}件見つかりました。削除して端末の容量を空けますか？',gcDone:'件の不要な録音を削除しました',
naLbl:'質問しなかった（採点対象外）',nextUnrec:'次の未録音へ',nextUnscored:'次の未採点へ',nextUnscoredS:'次の未採点',backS:'一覧へ',allRec:'すべて録音済みです',allScored:'未採点の項目はありません',
recBusy:'録音中です。先に「停止」を押してください',noRecGroup:'録音のない項目（{n}）',
spd:'速度',pauseAll:'再生を停止',sumTimes:'回受験',added:'追加済み',prevLbl:'前回',extraSec:'過去の項目（現在の設定にない質問）',
resetCnt:'（録音{n}件を削除します。元に戻せません）',
pass:'合格',fail:'不合格',pfLbl:'合否',passCnt:'合格',oldScore:'旧5段階評価',csvPass:'合格数（合格/採点）',chRate:'合格率の推移（%）',chSecRate:'分野別の合格率（%）',chItem:'設問別の合否（直近）'},
en:{wakeNote:'Keep the screen on while recording (recording stops if the screen turns off)',recCut:'Recording stopped unexpectedly (saved up to {s}s). Another app or a call may have taken the microphone. Use "Continue recording" for the rest',recCutStat:'Stopped early (saved up to {s}s)',recHidStop:'Recording stopped because the screen turned off (saved up to {s}s). Use "Continue recording" for the rest',recPause:'Pause',recResume:'Resume',recPaused:'Paused',pauseNA:'Pause is not supported on this device',recCont:'Continue recording',recAppended:'Added the continuation after the previous take',mergeFail:'Could not join the continuation to the previous take. The previous take is unchanged (you can download the continuation)',mergeFailStat:'Could not join the continuation (previous take is safe)',liveFound:'Interrupted recording found: {e} / {q} (about {s}s, {t})',liveMore:'+{n} more',liveRestore:'Restore interrupted recording',liveDiscard:'Discard',liveDiscardQ:'Delete the interrupted recording? This cannot be undone.',liveRestored:'Interrupted recording restored',liveNoSess:'No exam to restore into. Save the current exam first, or download the recording',liveReplace:'This question already has a recording. Replace it with the interrupted recording?',undoClose:'Close',pfCleared:'Pass/fail cleared (not judged)',beepOpt:'Play a short sound when recording starts/stops (vibration is always on where supported)',
noItems:'No questions. Add questions in Settings or choose a question set',noItemsT:'No questions',goCfg:'Add questions in Settings',pickSet:'Choose a question set',
drvConnNoAuto:'● Connected, but auto-save is OFF (recordings stay on this device only; turn it on with the checkbox below)',gAutoOn:'Auto-save of recordings turned ON',gAutoWait:'Checking the connection. Auto-save of recordings will turn ON once it connects',gAutoPend:'Auto-save turns ON after the connection is confirmed (check the URL and passphrase, then tap "Test connection")',drvOn:'☁ Drive auto-save: ON',drvOff:'☁ Drive auto-save: OFF (recordings on this device only)',drvNone:'☁ Drive: not set up (recordings on this device only)',drvHint:'Recordings are saved on this device only (set up Drive saving in the "Settings" tab)',drvHintGo:'Set up Drive',needEe:'Enter the examinee name first (Drive saves into a folder with this name)',eeSwitch:'{n} recording(s) and {m} pass/fail mark(s) for {o} are not saved yet.\n\nOK = save {o}\'s exam first, then start {e}\'s exam\nCancel = just correct the name (the current recordings and marks will belong to {e})',eeSwitched:'Saved {o}\'s exam. Starting {e}\'s exam',eeSwitchFail:'Could not save {o}\'s exam, so the name was changed back',
saveErrMsg:'The exam could not be saved (device storage may be full). Your entries and recordings are still on this screen. Export a backup first, free up space, then press "Save again"',retrySave:'Save again',
recSaveFail:'Recording could not be saved on this device',recKeptOld:'(previous recording kept)',recRetryStore:'Save again',recDl:'Download this recording',pendTakeSave:'{n} recording(s) could not be saved on this device. If you save now, they will be lost.\nFirst use "Save again" or "Download this recording" on each question.\n\nSave anyway? (Cancel = go back without saving)',pendTakeReset:'({n} recording(s) not saved on this device will also be lost. Download them first)',
micInsecure:'The microphone cannot be used on this page. Open it with an https:// address',micInsecureS:'No mic – open via https',
micNotFound:'No microphone found. Check the earphone/microphone connection',micNotFoundS:'No microphone found',
micBusy:'Another app is using the microphone. End the call or disconnect the Bluetooth earphones, then record',micBusyS:'Mic in use (end the call)',
drvFailToast:'Could not send to Google Drive. It will resend automatically when online (or tap "☁ Not sent" on the question)',drvUnsent:'☁ Not sent (tap to resend)',
oldN:'{n} old-scale',oldAvg:'Old avg ',oldTag:'old',unconf:' (unconfirmed)',stPending:'Judged – to confirm',notAsked:' (not asked)',
oldReplace:'Replace the old 5-level score ({v}) with Pass/Fail? (the old score will be lost)',oldNA:'Remove the old 5-level score ({v}) and mark as "Not asked"?',
confirmScored:'Every recorded question has Pass/Fail. Confirm the scoring too?\n(Cancel = save as recorded only; you can confirm later in the "Score" tab)',
oldOnly:'Only old 5-level scores (not included in pass rate). See the History tab for the scores',
mixNote:'* For exams that include old 5-level scores, the pass rate uses only the Pass/Fail questions',
chPending:'There are judged exams waiting for confirmation. Open them in the "Score" tab and press "Save Score" to show them here',
stPartial:'Partly judged',partLbl:'Pass {p} · judged {j}/rec {m}',chPartial:'Some exams are only partly judged. Open them in the "Score" tab, judge the rest and press "Save Score" to show them here',
pfProg:'Pass/Fail {j} / Rec {n}',pfMiss:'{n} without ○/×',nextUnjudged:'Next unjudged',allJudged:'Every recorded question has ○/×',
savedScored:'Exam and scores saved. See the result in the "History" tab',cfgSavedSet:'Items saved (also to set "{n}")',
qsTitle:'Question set',qsCur:'Active set',qsNone:'(unsaved layout)',qsSaveNew:'Save as a new set (name it)',qsApply:'Switch',qsRen:'Rename',qsDel:'Delete',
qsNamePrompt:'Enter a set name',
qsSwConfirm:'Switch to the saved contents of set "{n}"? Edits not saved with "Save Items" will be lost (past exam data is kept).',
qsDelConfirm:'Delete set "{n}"? (past exam data is kept)',
qsSaved:'Set saved',qsApplied:'Switched to set',qsDeleted:'Set deleted',
qbTitle:'Preset question sets (templates)',qbReplace:'Replace items',qbAppend:'Append items',
qbRepConfirm:'Replace current items with preset "{n}"? (past exam data is kept)',
qbApplied:'Preset applied',qbNone:'Presets (qbank.js) not loaded',
dirty:'Unsaved changes',dirtyLeave:'Exam items have unsaved changes. Leave without saving? (changes will be discarded)',
delSecConfirm:'Delete this section and all its questions?',cfgNote:'Deleting/replacing questions does not remove past scores, recordings or transcripts from history and CSV',
storeFail:'Save failed (device storage may be full). Export a backup from Settings',
gcConfirm:'{n} recording(s) belong to no session. Delete them to free space?',gcDone:' orphan recording(s) deleted',
naLbl:'Not asked (excluded from scoring)',nextUnrec:'Next unrecorded',nextUnscored:'Next unscored',nextUnscoredS:'Next',backS:'List',allRec:'All items recorded',allScored:'Nothing left to score',
recBusy:'Recording in progress — press "Stop" first',noRecGroup:'Items without recording ({n})',
spd:'Speed',pauseAll:'Pause playback',sumTimes:' exams',sumTimes1:' exam',added:'Added',extraSec:'Past items (not in current settings)',prevLbl:'Prev',
resetCnt:'({n} recording(s) will be deleted. This cannot be undone)',
pass:'Pass',fail:'Fail',pfLbl:'Pass/Fail',passCnt:'Passed',oldScore:'Old 5-level score',csvPass:'Passed (pass/scored)',chRate:'Pass rate trend (%)',chSecRate:'Pass rate by section (%)',chItem:'Pass/Fail by question (latest)'},
vi:{wakeNote:'Đừng tắt màn hình khi đang ghi âm (màn hình tắt thì ghi âm sẽ dừng)',recCut:'Ghi âm bị dừng giữa chừng (đã lưu đến {s} giây). Có thể ứng dụng khác hoặc cuộc gọi đã chiếm micro. Hãy dùng "Ghi tiếp" để ghi phần còn lại',recCutStat:'Dừng giữa chừng (đã lưu đến {s} giây)',recHidStop:'Đã dừng ghi âm vì màn hình tắt (đã lưu đến {s} giây). Hãy dùng "Ghi tiếp" để ghi phần còn lại',recPause:'Tạm dừng',recResume:'Tiếp tục',recPaused:'Đang tạm dừng',pauseNA:'Thiết bị này không hỗ trợ tạm dừng',recCont:'Ghi tiếp',recAppended:'Đã thêm phần ghi tiếp vào sau bản ghi trước',mergeFail:'Không thể nối phần ghi tiếp vào bản ghi trước. Bản ghi trước vẫn còn nguyên (có thể tải phần ghi tiếp)',mergeFailStat:'Không nối được phần ghi tiếp (bản ghi trước vẫn an toàn)',liveFound:'Có bản ghi bị gián đoạn: {e} / {q} (khoảng {s} giây, {t})',liveMore:'và {n} bản khác',liveRestore:'Khôi phục bản ghi bị gián đoạn',liveDiscard:'Bỏ',liveDiscardQ:'Xóa bản ghi bị gián đoạn? Không thể hoàn tác.',liveRestored:'Đã khôi phục bản ghi bị gián đoạn',liveNoSess:'Không có bài thi để khôi phục vào. Hãy lưu bài thi hiện tại trước, hoặc tải bản ghi xuống',liveReplace:'Câu này đã có bản ghi. Thay bằng bản ghi bị gián đoạn?',undoClose:'Đóng',pfCleared:'Đã hủy đạt/không đạt (chưa đánh giá)',beepOpt:'Phát âm ngắn khi bắt đầu/dừng ghi âm (rung luôn bật trên thiết bị hỗ trợ)',
noItems:'Chưa có câu hỏi. Hãy thêm câu hỏi ở tab Cài đặt hoặc chọn bộ câu hỏi',noItemsT:'Chưa có câu hỏi',goCfg:'Thêm câu hỏi ở tab Cài đặt',pickSet:'Chọn bộ câu hỏi',
drvConnNoAuto:'● Kết nối OK, nhưng tự động lưu đang TẮT (bản ghi chỉ ở máy này; bật bằng ô đánh dấu bên dưới)',gAutoOn:'Đã BẬT tự động lưu bản ghi âm',gAutoWait:'Đang kiểm tra kết nối. Khi kết nối được, tự động lưu bản ghi âm sẽ BẬT',gAutoPend:'Tự động lưu sẽ BẬT sau khi kết nối được xác nhận (kiểm tra URL và mật khẩu, rồi bấm "Kiểm tra kết nối")',drvOn:'☁ Tự động lưu Drive: BẬT',drvOff:'☁ Tự động lưu Drive: TẮT (bản ghi chỉ ở máy này)',drvNone:'☁ Drive: chưa cài đặt (bản ghi chỉ ở máy này)',drvHint:'Bản ghi âm chỉ được lưu trên máy này (cài đặt lưu Drive ở tab "Cài đặt")',drvHintGo:'Cài đặt Drive',needEe:'Hãy nhập tên thí sinh trước (Drive lưu vào thư mục mang tên này)',eeSwitch:'{n} bản ghi âm và {m} kết quả đạt/không đạt của {o} chưa được lưu.\n\nOK = lưu bài của {o} trước, rồi bắt đầu bài của {e}\nHủy = chỉ sửa tên (bản ghi và kết quả hiện tại sẽ thuộc về {e})',eeSwitched:'Đã lưu bài của {o}. Bắt đầu bài của {e}',eeSwitchFail:'Không lưu được bài của {o}, nên tên đã được trả lại như cũ',
saveErrMsg:'Không lưu được bài thi (có thể bộ nhớ thiết bị đã đầy). Thông tin và ghi âm vẫn còn trên màn hình này. Hãy xuất bản sao lưu trước, giải phóng bộ nhớ rồi nhấn "Lưu lại"',retrySave:'Lưu lại',
recSaveFail:'Không lưu được ghi âm vào thiết bị',recKeptOld:'(bản ghi trước vẫn còn)',recRetryStore:'Lưu lại',recDl:'Tải bản ghi âm này',pendTakeSave:'Có {n} bản ghi âm chưa lưu được vào thiết bị. Nếu lưu bây giờ, các bản ghi đó sẽ bị mất.\nHãy nhấn "Lưu lại" hoặc "Tải bản ghi âm này" ở từng câu trước.\n\nVẫn lưu? (Hủy = quay lại, không lưu)',pendTakeReset:'(Cả {n} bản ghi âm chưa lưu được vào thiết bị cũng sẽ bị mất. Hãy tải xuống trước)',
micInsecure:'Không dùng được micro trên trang này. Hãy mở bằng địa chỉ https://',micInsecureS:'Không có micro – mở bằng https',
micNotFound:'Không tìm thấy micro. Hãy kiểm tra kết nối tai nghe/micro',micNotFoundS:'Không tìm thấy micro',
micBusy:'Ứng dụng khác đang dùng micro. Hãy kết thúc cuộc gọi hoặc ngắt tai nghe Bluetooth rồi ghi âm',micBusyS:'Micro đang bận (kết thúc cuộc gọi)',
drvFailToast:'Không gửi được lên Google Drive. Sẽ tự gửi lại khi có mạng (hoặc chạm "☁ Chưa gửi" ở câu hỏi)',drvUnsent:'☁ Chưa gửi (chạm để gửi lại)',
oldN:'{n} câu điểm cũ',oldAvg:'Điểm cũ TB ',oldTag:'cũ',unconf:' (chưa xác nhận)',stPending:'Đã đánh giá – chờ xác nhận',notAsked:' (không hỏi)',
oldReplace:'Thay điểm cũ 5 mức ({v}) bằng Đạt/Không đạt? (điểm cũ sẽ mất)',oldNA:'Xóa điểm cũ 5 mức ({v}) và đánh dấu "Không hỏi"?',
confirmScored:'Tất cả câu đã ghi âm đều có Đạt/Không đạt. Xác nhận chấm điểm luôn?\n(Hủy = chỉ lưu ghi âm, có thể xác nhận sau ở thẻ "Chấm")',
oldOnly:'Chỉ có điểm cũ 5 mức (không tính tỷ lệ đạt). Xem điểm ở tab Lịch sử',
mixNote:'* Bài thi có điểm cũ 5 mức: tỷ lệ đạt chỉ tính các câu Đạt/Không đạt',
chPending:'Có bài thi đã đánh giá đang chờ xác nhận. Mở ở thẻ "Chấm" và nhấn "Lưu điểm" để hiển thị',
stPartial:'Đang chấm dở',partLbl:'Đạt {p} · đã đánh giá {j}/ghi âm {m}',chPartial:'Có bài thi mới đánh giá một phần. Mở ở thẻ "Chấm", đánh giá các câu còn lại và nhấn "Lưu điểm" để hiển thị',
pfProg:'Đạt/Không {j} / Ghi âm {n}',pfMiss:'{n} câu chưa chọn ○/×',nextUnjudged:'Câu chưa đánh giá tiếp theo',allJudged:'Tất cả câu đã ghi âm đều đã có ○/×',
savedScored:'Đã lưu bài thi và điểm. Xem kết quả ở thẻ "Lịch sử"',cfgSavedSet:'Đã lưu (cũng lưu vào bộ "{n}")',
qsTitle:'Bộ câu hỏi',qsCur:'Bộ hiện tại',qsNone:'(chưa lưu thành bộ)',qsSaveNew:'Lưu thành bộ mới (đặt tên)',qsApply:'Chuyển',qsRen:'Đổi tên',qsDel:'Xóa',
qsNamePrompt:'Nhập tên bộ',qbTitle:'Bộ câu hỏi mẫu',qbReplace:'Thay thế mục',qbAppend:'Thêm vào mục',
naLbl:'Không hỏi (không chấm)',nextUnrec:'Mục chưa ghi tiếp theo',nextUnscored:'Mục chưa chấm tiếp theo',nextUnscoredS:'Mục tiếp',backS:'Danh sách',allRec:'Đã ghi tất cả',allScored:'Không còn mục chưa chấm',
recBusy:'Đang ghi âm — hãy nhấn "Dừng" trước',noRecGroup:'Mục không có ghi âm ({n})',
spd:'Tốc độ',pauseAll:'Dừng phát',sumTimes:' lần thi',added:'Đã thêm',extraSec:'Mục cũ (không có trong cài đặt hiện tại)',prevLbl:'Lần trước',
resetCnt:'({n} bản ghi âm sẽ bị xóa. Không thể hoàn tác)',
pass:'Đạt',fail:'Không đạt',pfLbl:'Đạt/Không đạt',passCnt:'Đạt',oldScore:'Điểm cũ (5 mức)',
qsSwConfirm:'Chuyển sang nội dung đã lưu của bộ "{n}"? Các chỉnh sửa chưa nhấn "Lưu" sẽ bị mất (dữ liệu các bài thi trước vẫn giữ nguyên).',
qsDelConfirm:'Xóa bộ "{n}"? (dữ liệu các bài thi trước vẫn giữ nguyên)',
qsSaved:'Đã lưu bộ',qsApplied:'Đã chuyển bộ',qsDeleted:'Đã xóa bộ',
qbRepConfirm:'Thay các mục thi hiện tại bằng bộ mẫu "{n}"? (dữ liệu các bài thi trước vẫn giữ nguyên)',
qbApplied:'Đã áp dụng bộ mẫu',qbNone:'Chưa tải được bộ mẫu (qbank.js)',
dirty:'Có thay đổi chưa lưu',dirtyLeave:'Các mục thi có thay đổi chưa lưu. Rời đi mà không lưu? (thay đổi sẽ bị hủy)',
delSecConfirm:'Xóa phần này và tất cả câu hỏi trong đó?',cfgNote:'* Xóa hoặc thay câu hỏi thì điểm, ghi âm và bản ghi lời của các bài thi trước vẫn còn trong lịch sử và CSV',
storeFail:'Lưu thất bại (có thể bộ nhớ thiết bị đã đầy). Hãy xuất bản sao lưu ở tab Cài đặt',
gcConfirm:'Có {n} bản ghi âm không thuộc bài thi nào. Xóa để giải phóng bộ nhớ?',gcDone:' bản ghi âm thừa đã được xóa',
csvPass:'Số câu đạt (đạt/đã chấm)',chRate:'Xu hướng tỷ lệ đạt (%)',chSecRate:'Tỷ lệ đạt theo lĩnh vực (%)',chItem:'Đạt/Không đạt theo câu hỏi (gần nhất)'},
id:{wakeNote:'Jangan matikan layar saat merekam (rekaman berhenti jika layar mati)',recCut:'Rekaman berhenti di tengah jalan (tersimpan sampai {s} detik). Mungkin mikrofon diambil aplikasi lain atau panggilan. Gunakan "Lanjutkan rekaman" untuk sisanya',recCutStat:'Berhenti di tengah (tersimpan sampai {s} detik)',recHidStop:'Rekaman dihentikan karena layar mati (tersimpan sampai {s} detik). Gunakan "Lanjutkan rekaman" untuk sisanya',recPause:'Jeda',recResume:'Lanjut',recPaused:'Dijeda',pauseNA:'Perangkat ini tidak mendukung jeda',recCont:'Lanjutkan rekaman',recAppended:'Lanjutan ditambahkan setelah rekaman sebelumnya',mergeFail:'Lanjutan tidak dapat digabung ke rekaman sebelumnya. Rekaman sebelumnya tetap utuh (lanjutan bisa diunduh)',mergeFailStat:'Lanjutan tidak tergabung (rekaman sebelumnya aman)',liveFound:'Ada rekaman yang terputus: {e} / {q} (sekitar {s} detik, {t})',liveMore:'dan {n} lainnya',liveRestore:'Pulihkan rekaman yang terputus',liveDiscard:'Buang',liveDiscardQ:'Hapus rekaman yang terputus? Tidak bisa dibatalkan.',liveRestored:'Rekaman yang terputus sudah dipulihkan',liveNoSess:'Tidak ada ujian tujuan pemulihan. Simpan ujian sekarang dulu, atau unduh rekamannya',liveReplace:'Soal ini sudah punya rekaman. Ganti dengan rekaman yang terputus?',undoClose:'Tutup',pfCleared:'Lulus/tidak lulus dibatalkan (belum dinilai)',beepOpt:'Bunyikan suara pendek saat mulai/berhenti merekam (getar selalu aktif di perangkat yang mendukung)',
noItems:'Belum ada pertanyaan. Tambahkan pertanyaan di tab Pengaturan atau pilih set pertanyaan',noItemsT:'Belum ada pertanyaan',goCfg:'Tambah pertanyaan di Pengaturan',pickSet:'Pilih set pertanyaan',
drvConnNoAuto:'● Terhubung, tetapi simpan otomatis MATI (rekaman hanya di perangkat ini; nyalakan dengan kotak centang di bawah)',gAutoOn:'Simpan otomatis rekaman DINYALAKAN',gAutoWait:'Memeriksa koneksi. Simpan otomatis rekaman akan NYALA setelah terhubung',gAutoPend:'Simpan otomatis NYALA setelah koneksi dipastikan (periksa URL dan kata sandi, lalu ketuk "Tes koneksi")',drvOn:'☁ Simpan otomatis Drive: NYALA',drvOff:'☁ Simpan otomatis Drive: MATI (rekaman hanya di perangkat ini)',drvNone:'☁ Drive: belum diatur (rekaman hanya di perangkat ini)',drvHint:'Rekaman hanya disimpan di perangkat ini (atur penyimpanan Drive di tab "Pengaturan")',drvHintGo:'Atur Drive',needEe:'Masukkan nama peserta dulu (Drive menyimpan ke folder dengan nama ini)',eeSwitch:'{n} rekaman dan {m} hasil lulus/tidak milik {o} belum disimpan.\n\nOK = simpan ujian {o} dulu, lalu mulai ujian {e}\nBatal = hanya perbaiki nama (rekaman dan hasil saat ini menjadi milik {e})',eeSwitched:'Ujian {o} disimpan. Memulai ujian {e}',eeSwitchFail:'Ujian {o} tidak dapat disimpan, jadi nama dikembalikan',
saveErrMsg:'Ujian tidak dapat disimpan (penyimpanan perangkat mungkin penuh). Isian dan rekaman masih ada di layar ini. Ekspor cadangan dulu, kosongkan ruang, lalu tekan "Simpan lagi"',retrySave:'Simpan lagi',
recSaveFail:'Rekaman tidak dapat disimpan di perangkat',recKeptOld:'(rekaman sebelumnya masih ada)',recRetryStore:'Simpan lagi',recDl:'Unduh rekaman ini',pendTakeSave:'Ada {n} rekaman yang belum tersimpan di perangkat. Jika disimpan sekarang, rekaman itu akan hilang.\nGunakan "Simpan lagi" atau "Unduh rekaman ini" pada setiap soal terlebih dahulu.\n\nTetap simpan? (Batal = kembali tanpa menyimpan)',pendTakeReset:'({n} rekaman yang belum tersimpan di perangkat juga akan hilang. Unduh dulu)',
micInsecure:'Mikrofon tidak dapat dipakai di halaman ini. Buka dengan alamat https://',micInsecureS:'Mik tidak bisa – buka via https',
micNotFound:'Mikrofon tidak ditemukan. Periksa sambungan earphone/mikrofon',micNotFoundS:'Mikrofon tidak ditemukan',
micBusy:'Aplikasi lain sedang memakai mikrofon. Akhiri panggilan atau putuskan earphone Bluetooth, lalu rekam',micBusyS:'Mik sedang dipakai (akhiri panggilan)',
drvFailToast:'Gagal mengirim ke Google Drive. Akan dikirim ulang otomatis saat online (atau ketuk "☁ Belum terkirim" di pertanyaan)',drvUnsent:'☁ Belum terkirim (ketuk untuk kirim ulang)',
oldN:'{n} nilai lama',oldAvg:'Rata nilai lama ',oldTag:'lama',unconf:' (belum final)',stPending:'Sudah dinilai – tunggu konfirmasi',notAsked:' (tidak ditanya)',
oldReplace:'Ganti nilai lama 5 tingkat ({v}) dengan Lulus/Tidak lulus? (nilai lama akan hilang)',oldNA:'Hapus nilai lama 5 tingkat ({v}) dan tandai "Tidak ditanya"?',
confirmScored:'Semua pertanyaan yang direkam sudah Lulus/Tidak lulus. Konfirmasi penilaian juga?\n(Batal = simpan rekaman saja; bisa dikonfirmasi nanti di tab "Nilai")',
oldOnly:'Hanya nilai lama 5 tingkat (tidak dihitung tingkat lulus). Lihat nilai di tab Riwayat',
mixNote:'* Untuk ujian dengan nilai lama 5 tingkat, tingkat lulus hanya dari pertanyaan Lulus/Tidak lulus',
chPending:'Ada ujian yang sudah dinilai dan menunggu konfirmasi. Buka di tab "Nilai" lalu tekan "Simpan Nilai"',
stPartial:'Penilaian belum selesai',partLbl:'Lulus {p} · dinilai {j}/rekam {m}',chPartial:'Ada ujian yang baru sebagian dinilai. Buka di tab "Nilai", nilai sisanya, lalu tekan "Simpan Nilai" agar tampil di sini',
pfProg:'Lulus/Tidak {j} / Rekam {n}',pfMiss:'{n} belum ○/×',nextUnjudged:'Belum dinilai berikutnya',allJudged:'Semua yang direkam sudah ○/×',
savedScored:'Ujian dan nilai tersimpan. Lihat hasil di tab "Riwayat"',cfgSavedSet:'Tersimpan (juga ke set "{n}")',
qsTitle:'Set pertanyaan',qsCur:'Set aktif',qsNone:'(belum disimpan sebagai set)',qsSaveNew:'Simpan sebagai set baru (beri nama)',qsApply:'Ganti',qsRen:'Ubah nama',qsDel:'Hapus',
qsNamePrompt:'Masukkan nama set',qbTitle:'Set pertanyaan preset',qbReplace:'Ganti item',qbAppend:'Tambahkan item',
naLbl:'Tidak ditanya (tidak dinilai)',nextUnrec:'Item belum direkam berikutnya',nextUnscored:'Item belum dinilai berikutnya',nextUnscoredS:'Berikutnya',backS:'Daftar',allRec:'Semua sudah direkam',allScored:'Tidak ada yang belum dinilai',
recBusy:'Sedang merekam — tekan "Stop" dulu',noRecGroup:'Item tanpa rekaman ({n})',
spd:'Kecepatan',pauseAll:'Jeda pemutaran',sumTimes:' ujian',added:'Sudah ditambah',extraSec:'Item lama (tidak ada di pengaturan)',prevLbl:'Sebelumnya',
resetCnt:'({n} rekaman akan dihapus. Tidak dapat dibatalkan)',
pass:'Lulus',fail:'Tidak lulus',pfLbl:'Lulus/Tidak',passCnt:'Lulus',oldScore:'Nilai lama (5 tingkat)',
qsSwConfirm:'Ganti ke isi tersimpan set "{n}"? Perubahan yang belum di-"Simpan" akan hilang (data ujian sebelumnya tetap ada).',
qsDelConfirm:'Hapus set "{n}"? (data ujian sebelumnya tetap ada)',
qsSaved:'Set disimpan',qsApplied:'Set diganti',qsDeleted:'Set dihapus',
qbRepConfirm:'Ganti item ujian saat ini dengan preset "{n}"? (data ujian sebelumnya tetap ada)',
qbApplied:'Preset diterapkan',qbNone:'Preset (qbank.js) belum dimuat',
dirty:'Ada perubahan yang belum disimpan',dirtyLeave:'Item ujian memiliki perubahan yang belum disimpan. Keluar tanpa menyimpan? (perubahan akan dibuang)',
delSecConfirm:'Hapus bagian ini beserta semua pertanyaannya?',cfgNote:'* Menghapus/mengganti pertanyaan tidak menghapus nilai, rekaman, dan transkrip ujian sebelumnya dari riwayat dan CSV',
storeFail:'Gagal menyimpan (penyimpanan perangkat mungkin penuh). Ekspor cadangan dari tab Pengaturan',
gcConfirm:'Ada {n} rekaman yang tidak termasuk ujian mana pun. Hapus untuk mengosongkan ruang?',gcDone:' rekaman tak terpakai dihapus',
csvPass:'Jumlah lulus (lulus/dinilai)',chRate:'Tren tingkat lulus (%)',chSecRate:'Tingkat lulus per bidang (%)',chItem:'Lulus/Tidak lulus per pertanyaan (terbaru)'}
};
function t2(k){const d=TX2[lang]||TX2.ja;return d[k]||TX2.en[k]||TX2.ja[k]||k}
/* 採点値→表示ラベル（合格/不合格。旧5段階の数値は「4 — 良好」形式） */
function pfLabel(v){return isPF(v)?t2(v):(isOld(v)?Number(v)+' — '+t('s'+Number(v)):(v!=null?String(v):''))}
/* 各問の採点表示（旧5段階は「旧 4 — 良好」と明示＝合否と取り違えない） */
function scoreTxt(v){return isOld(v)?t2('oldTag')+' '+pfLabel(v):pfLabel(v)}
/* 一覧行の状態バッジ・結果（採点済／録音した全問に○×が付いた確定待ち／○×が途中までの採点途中／録音のみ） */
function rowRes(r){
  const sc=r.status==='scored',pf=!sc&&hasPF(r),full=pf&&judgeState(r).full;
  const nU=typeof unsentCount==='function'?unsentCount(r):0; // ドライブ未送信の録音数（一覧でも分かるように）
  const badge=(sc?`<span class="badge scored">${t('stScored')}</span>`:full?`<span class="badge pend">${esc(t2('stPending'))}</span>`:pf?`<span class="badge part">${esc(t2('stPartial'))}</span>`:`<span class="badge rec">${t('stRec')}</span>`)
    +(nU?`<span class="badge unsent" title="${esc(t2('drvUnsent'))}" style="background:transparent;color:var(--s1);border:1px solid var(--s1)">☁ ${nU}</span>`:'');
  if(!sc&&!pf)return{badge,cls:'',lbl:'–'};
  const lbl=sc?resLbl(r):pendLbl(r);
  // 採点途中は合否の色を付けない（判定した問だけ全問合格＝緑に見せない）
  return{badge,cls:(sc?resCls(r):full?resCls(r,true):'old')+(lbl.length>5?' lng':''),lbl};
}
